version: '3'

services:
  postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=rdenadai
      - POSTGRESQL_PASSWORD=rdenadai
      - POSTGRESQL_DATABASE=gotodo

volumes:
  postgresql_master_data:
